import Options from "@/components/options";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main><Link href="/" className="text-5xl font-semibold">
          <img src="/logo.svg" alt="logo" className="m-4 size-24" />
        </Link>
        <div className="flex w-full flex-col items-center">
          <Options />
          {children}
        </div></main>
        <Toaster />
      </body>
    </html>
  );
}
